name: Reusable Terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - run: terraform validate