name: Pipeline CI/CD

on:
  push:
    branches: [feature/*, develop, main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente de deploy (dev, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read
  actions: write
  pull-requests: write

jobs:

  test:
    uses: ./.github/workflows/01_test.yml

  terraform:
    needs: test
    if: |
      (github.ref_name == 'develop' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch') &&
      needs.test.result == 'success'
    uses: ./.github/workflows/02_terraform.yml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name == 'develop' && 'dev' || 'prod' }}
    secrets:
      aws-assume-role-arn: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment == 'dev' && secrets.AWS_ASSUME_ROLE_ARN_DEV || secrets.AWS_ASSUME_ROLE_ARN_PROD) || github.ref_name == 'develop' && secrets.AWS_ASSUME_ROLE_ARN_DEV || secrets.AWS_ASSUME_ROLE_ARN_PROD }}
      aws-statefile-s3-bucket: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment == 'dev' && secrets.AWS_STATEFILE_S3_BUCKET_DEV || secrets.AWS_STATEFILE_S3_BUCKET_PROD) || github.ref_name == 'develop' && secrets.AWS_STATEFILE_S3_BUCKET_DEV || secrets.AWS_STATEFILE_S3_BUCKET_PROD }}
      aws-lock-dynamodb-table: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment == 'dev' && secrets.AWS_LOCK_DYNAMODB_TABLE_DEV || secrets.AWS_LOCK_DYNAMODB_TABLE_PROD) || github.ref_name == 'develop' && secrets.AWS_LOCK_DYNAMODB_TABLE_DEV || secrets.AWS_LOCK_DYNAMODB_TABLE_PROD }}
      aws-tmdb-secret-arn: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment == 'dev' && secrets.AWS_TMDB_SECRET_ARN_DEV || secrets.AWS_TMDB_SECRET_ARN_PROD) || github.ref_name == 'develop' && secrets.AWS_TMDB_SECRET_ARN_DEV || secrets.AWS_TMDB_SECRET_ARN_PROD }}
      notification-email: ${{ secrets.NOTIFICATION_EMAIL }}
      infracost-api-key: ${{ secrets.INFRACOST_API_KEY }}

  deploy-lightsail:
    needs: terraform
    if: |
      (github.ref_name == 'develop' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch') &&
      needs.terraform.result == 'success' &&
      needs.terraform.outputs.was_destroyed != 'true'
    uses: ./.github/workflows/04_deploy_lightsail.yml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name == 'develop' && 'dev' || 'prod' }}
    secrets:
      aws-assume-role-arn: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment == 'dev' && secrets.AWS_ASSUME_ROLE_ARN_DEV || secrets.AWS_ASSUME_ROLE_ARN_PROD) || github.ref_name == 'develop' && secrets.AWS_ASSUME_ROLE_ARN_DEV || secrets.AWS_ASSUME_ROLE_ARN_PROD }}
      aws-statefile-s3-bucket: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment == 'dev' && secrets.AWS_STATEFILE_S3_BUCKET_DEV || secrets.AWS_STATEFILE_S3_BUCKET_PROD) || github.ref_name == 'develop' && secrets.AWS_STATEFILE_S3_BUCKET_DEV || secrets.AWS_STATEFILE_S3_BUCKET_PROD }}
      aws-lock-dynamodb-table: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.environment == 'dev' && secrets.AWS_LOCK_DYNAMODB_TABLE_DEV || secrets.AWS_LOCK_DYNAMODB_TABLE_PROD) || github.ref_name == 'develop' && secrets.AWS_LOCK_DYNAMODB_TABLE_DEV || secrets.AWS_LOCK_DYNAMODB_TABLE_PROD }}
      llm-api-key: ${{ secrets.LLM_API_KEY }}
      filmbot-password: ${{ secrets.FILMBOT_PASSWORD }}

  auto-pr-feature:
    needs: test
    if: |
      startsWith(github.ref_name, 'feature/') &&
      needs.test.result == 'success'
    uses: ./.github/workflows/03_pr_auto.yml
    with:
      branch_name: ${{ github.ref_name }}
    permissions:
      contents: write
      pull-requests: write

  auto-pr-environment:
    needs: [deploy-lightsail]
    if: |
      github.ref_name == 'develop' &&
      needs.deploy-lightsail.result == 'success'
    uses: ./.github/workflows/03_pr_auto.yml
    with:
      branch_name: ${{ github.ref_name }}
    permissions:
      contents: write
      pull-requests: write
