name: "FEATURE DEPLOY"

on:
  push:
    branches:
      - feature/*

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          head: ${{ github.ref_name }}
          base: develop
          title: "develop <- ${{ github.ref_name }}"
          body: "PR criado automaticamente a partir de novos commits."
          labels: automatic, pr