name: Automatic PR

on:
  push:
    branches:
      - feature/* # A branch que recebe novos commits (origem)

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }} # Checkout da branch de origem

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }} # A branch que será enviada
          base: develop # A branch de destino (ex: main, master, develop)
          title: "develop <- ${{ github.ref_name }}"
          body: "PR criado automaticamente a partir de novos commits."
          labels: automatic, pr
