name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
    secrets:
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-statefile-s3-bucket: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop # Checkout da branch de origem

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop # A branch que será enviada
          base: release # A branch de destino (ex: main, master, develop)
          title: "release <- develop"
          body: "PR criado automaticamente a partir de novos commits."
          labels: automatic, pr