name: "HOM DEPLOY"

on:
  push:
    branches:
      - release

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/0-terraform.yml
    with:
      environment: hom
    secrets:
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-statefile-s3-bucket: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}