# Nome identificador do workflow que aparecerá na interface do GitHub Actions
name: Test (Reusable)

# Define que este workflow é "Reutilizável" (pode ser chamado por outros arquivos .yml)
on:
  workflow_call:

jobs:
  test:
    # Especifica o ambiente de execução (neste caso, uma máquina virtual Linux zerada)
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório para dentro da máquina virtual
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Prepara o ambiente instalando a versão 3.12 do interpretador Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Gerencia as bibliotecas necessárias
      - name: Install dependencies
        run: |
          # Atualiza o instalador de pacotes (pip) para a versão mais recente
          python -m pip install --upgrade pip
          # Instala o framework de teste (pytest) e o plugin de cobertura (pytest-cov)
          pip install pytest pytest-cov
          # Verifica se existe um arquivo de dependências específico de teste e o instala
          if [ -f test/requirements_test.txt ]; then
            pip install -r test/requirements_test.txt
          fi

      # 4. Configura o PYTHONPATH para que o Python consiga importar seus módulos (pasta app, etc)
      # Adicionar o diretório raiz ao GITHUB_ENV resolve erros de "ModuleNotFoundError"
      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      # 5. Executa os testes e aplica a barreira de qualidade (Quality Gate)
      - name: Run tests with Coverage Gate
        run: |
          # pytest: executa os testes
          # --cov=.: mede a cobertura de código a partir da raiz
          # --cov-report=term-missing: lista no terminal quais linhas não foram testadas
          # --cov-report=xml: gera um arquivo técnico (coverage.xml) para ferramentas externas
          # --cov-fail-under=70: interrompe a pipeline com erro se a cobertura for menor que 70%
          pytest --cov=. \
                 --cov-report=term-missing \
                 --cov-report=xml \
                 --cov-fail-under=70