# Nome da Pipeline que aparece no topo da aba Actions do GitHub
name: Pipeline CI/CD

# Define os gatilhos: a esteira roda sempre que houver um push nessas branches específicas
on:
  push:
    branches: [feature/*, develop, release, main]

# Permissões padrão para o token do GitHub (necessário para autenticação OIDC/AWS)
permissions:
  id-token: write
  contents: read

jobs:

  # 1. Job de Testes: Chama o workflow reutilizável que criamos (ci-test.yml)
  # Roda para todas as branches configuradas no 'on'
  test:
    uses: ./.github/workflows/ci-test.yml

  # 2. Job de Terraform: Realiza o deploy da infraestrutura
  terraform:
    needs: test # Só inicia se o job 'test' terminar com sucesso
    # Condição: Só roda em branches de ambiente (dev, hom, prod) e se o teste passou
    if: (github.ref_name == 'develop' || github.ref_name == 'release' || github.ref_name == 'main') && needs.test.result == 'success'
    uses: ./.github/workflows/tf-infra.yml
    with:
      # Lógica para decidir o ambiente AWS baseado no nome da branch atual
      environment: ${{ github.ref_name == 'develop' && 'dev' || github.ref_name == 'release' && 'hom' || 'prod' }}
    secrets:
      # Passagem de segredos necessários para a autenticação na AWS via OIDC
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-statefile-s3-bucket: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}

  # 3. Auto PR para Feature: Promove o código de feature/* para develop
  auto-pr-feature:
    needs: test # Só depende dos testes passarem
    if: (startsWith(github.ref_name, 'feature/') && needs.test.result == 'success')
    uses: ./.github/workflows/pr-auto.yml
    with:
      branch_name: ${{ github.ref_name }}
    permissions: # Permissões extras para criar PR e editar conteúdo
      contents: write
      pull-requests: write

  # 4. Auto PR para Ambientes: Promove develop -> release ou release -> main
  auto-pr-environment:
    needs: terraform # Só inicia se o deploy do Terraform (validar infra) deu certo
    # Só roda para develop ou release (main não tem destino posterior para promover)
    if: (github.ref_name == 'develop' || github.ref_name == 'release') && needs.terraform.result == 'success'
    uses: ./.github/workflows/pr-auto.yml
    with:
      branch_name: ${{ github.ref_name }}
    permissions:
      contents: write
      pull-requests: write