name: Auto PR Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - develop
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔍 Descobrir destino do PR
      - name: Define base branch
        id: branch
        run: |
          if [[ "${GITHUB_REF_NAME}" == feature/* ]]; then
            echo "base=develop" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "base=release" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "release" ]]; then
            echo "base=main" >> $GITHUB_OUTPUT
          else
            echo "Branch não suportada"
            exit 1
          fi

      # (Opcional) Terraform validate
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Validate
        run: |
          cd infra
          terraform init -backend=false
          terraform validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}